services:
  - type: web
    name: telegram-mindfulness-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: your_bot_token_here
      - key: YOUR_CHAT_ID
        value: your_chat_id_here
